// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_sample_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_TVALID,
        out_r_TREADY,
        reg_8_reload,
        reg_7_reload,
        reg_6_reload,
        reg_5_reload,
        reg_4_reload,
        reg_3_reload,
        reg_2_reload,
        reg_1_reload,
        reg_reload,
        in_r_TDATA,
        in_r_TREADY,
        out_r_TDATA,
        out_r_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_r_TVALID;
input   out_r_TREADY;
input  [31:0] reg_8_reload;
input  [31:0] reg_7_reload;
input  [31:0] reg_6_reload;
input  [31:0] reg_5_reload;
input  [31:0] reg_4_reload;
input  [31:0] reg_3_reload;
input  [31:0] reg_2_reload;
input  [31:0] reg_1_reload;
input  [31:0] reg_reload;
input  [31:0] in_r_TDATA;
output   in_r_TREADY;
output  [31:0] out_r_TDATA;
output   out_r_TVALID;

reg ap_idle;
reg in_r_TREADY;
reg out_r_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln16_reg_483;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln16_fu_224_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_r_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    out_r_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] y_fu_362_p2;
reg   [31:0] y_reg_487;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [6:0] n_fu_64;
wire   [6:0] add_ln16_fu_230_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_n_1;
wire    ap_block_pp0_stage0;
reg   [31:0] reg_fu_68;
reg   [31:0] reg_1_fu_72;
reg   [31:0] reg_2_fu_76;
reg   [31:0] reg_3_fu_80;
reg   [31:0] reg_4_fu_84;
reg   [31:0] reg_5_fu_88;
reg   [31:0] reg_6_fu_92;
reg   [31:0] reg_7_fu_96;
reg   [31:0] reg_8_fu_100;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [31:0] tmp_fu_288_p2;
wire   [31:0] tmp1_fu_294_p2;
wire   [31:0] empty_fu_300_p2;
wire   [31:0] tmp3_fu_312_p2;
wire   [31:0] empty_10_fu_318_p2;
wire   [30:0] trunc_ln16_1_fu_272_p1;
wire   [30:0] trunc_ln16_fu_268_p1;
wire   [30:0] tmp61_fu_330_p2;
wire   [31:0] sub_ln25_fu_276_p2;
wire   [31:0] tmp7_fu_336_p3;
wire   [31:0] tmp2_fu_306_p2;
wire   [31:0] tmp4_fu_324_p2;
wire   [31:0] add_ln25_1_fu_350_p2;
wire   [31:0] shl_ln25_fu_282_p2;
wire   [31:0] sub_ln25_1_fu_356_p2;
wire   [31:0] add_ln25_fu_344_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 n_fu_64 = 7'd0;
#0 reg_fu_68 = 32'd0;
#0 reg_1_fu_72 = 32'd0;
#0 reg_2_fu_76 = 32'd0;
#0 reg_3_fu_80 = 32'd0;
#0 reg_4_fu_84 = 32'd0;
#0 reg_5_fu_88 = 32'd0;
#0 reg_6_fu_92 = 32'd0;
#0 reg_7_fu_96 = 32'd0;
#0 reg_8_fu_100 = 32'd0;
#0 ap_done_reg = 1'b0;
end

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln16_fu_224_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_64 <= add_ln16_fu_230_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_1_fu_72 <= reg_2_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_1_fu_72 <= reg_5_fu_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_2_fu_76 <= reg_4_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_2_fu_76 <= reg_6_fu_92;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_3_fu_80 <= reg_6_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_3_fu_80 <= reg_7_fu_96;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_4_fu_84 <= reg_8_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_4_fu_84 <= reg_8_fu_100;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_5_fu_88 <= reg_1_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_5_fu_88 <= reg_fu_68;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_6_fu_92 <= reg_3_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_6_fu_92 <= reg_1_fu_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_7_fu_96 <= reg_5_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_7_fu_96 <= reg_2_fu_76;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_8_fu_100 <= reg_7_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_8_fu_100 <= reg_3_fu_80;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reg_fu_68 <= reg_reload;
        end else if (((icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            reg_fu_68 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln16_reg_483 <= icmp_ln16_fu_224_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_reg_487 <= y_fu_362_p2;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_224_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln16_reg_483 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TDATA_blk_n = in_r_TVALID;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln16_reg_483 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TREADY = 1'b1;
    end else begin
        in_r_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_TDATA_blk_n = out_r_TREADY;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_r_TVALID = 1'b1;
    end else begin
        out_r_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_230_p2 = (ap_sig_allocacmp_n_1 + 7'd1);

assign add_ln25_1_fu_350_p2 = (tmp2_fu_306_p2 + tmp4_fu_324_p2);

assign add_ln25_fu_344_p2 = (sub_ln25_fu_276_p2 + tmp7_fu_336_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_r_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((icmp_ln16_reg_483 == 1'd0) & (in_r_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_10_fu_318_p2 = tmp3_fu_312_p2 << 32'd2;

assign empty_fu_300_p2 = tmp1_fu_294_p2 << 32'd2;

assign icmp_ln16_fu_224_p2 = ((ap_sig_allocacmp_n_1 == 7'd100) ? 1'b1 : 1'b0);

assign out_r_TDATA = y_reg_487;

assign shl_ln25_fu_282_p2 = reg_fu_68 << 32'd2;

assign sub_ln25_1_fu_356_p2 = (add_ln25_1_fu_350_p2 - shl_ln25_fu_282_p2);

assign sub_ln25_fu_276_p2 = (reg_8_fu_100 - reg_4_fu_84);

assign tmp1_fu_294_p2 = (tmp_fu_288_p2 + reg_5_fu_88);

assign tmp2_fu_306_p2 = (empty_fu_300_p2 - tmp1_fu_294_p2);

assign tmp3_fu_312_p2 = (in_r_TDATA + reg_6_fu_92);

assign tmp4_fu_324_p2 = (empty_10_fu_318_p2 + tmp3_fu_312_p2);

assign tmp61_fu_330_p2 = (trunc_ln16_1_fu_272_p1 - trunc_ln16_fu_268_p1);

assign tmp7_fu_336_p3 = {{tmp61_fu_330_p2}, {1'd0}};

assign tmp_fu_288_p2 = (reg_2_fu_76 - reg_7_fu_96);

assign trunc_ln16_1_fu_272_p1 = reg_3_fu_80[30:0];

assign trunc_ln16_fu_268_p1 = reg_1_fu_72[30:0];

assign y_fu_362_p2 = (sub_ln25_1_fu_356_p2 + add_ln25_fu_344_p2);

endmodule //fir_fir_Pipeline_sample_loop
