// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_8_out,
        reg_8_out_ap_vld,
        reg_7_out,
        reg_7_out_ap_vld,
        reg_6_out,
        reg_6_out_ap_vld,
        reg_5_out,
        reg_5_out_ap_vld,
        reg_4_out,
        reg_4_out_ap_vld,
        reg_3_out,
        reg_3_out_ap_vld,
        reg_2_out,
        reg_2_out_ap_vld,
        reg_1_out,
        reg_1_out_ap_vld,
        reg_out,
        reg_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] reg_8_out;
output   reg_8_out_ap_vld;
output  [31:0] reg_7_out;
output   reg_7_out_ap_vld;
output  [31:0] reg_6_out;
output   reg_6_out_ap_vld;
output  [31:0] reg_5_out;
output   reg_5_out_ap_vld;
output  [31:0] reg_4_out;
output   reg_4_out_ap_vld;
output  [31:0] reg_3_out;
output   reg_3_out_ap_vld;
output  [31:0] reg_2_out;
output   reg_2_out_ap_vld;
output  [31:0] reg_1_out;
output   reg_1_out_ap_vld;
output  [31:0] reg_out;
output   reg_out_ap_vld;

reg ap_idle;
reg reg_8_out_ap_vld;
reg reg_7_out_ap_vld;
reg reg_6_out_ap_vld;
reg reg_5_out_ap_vld;
reg reg_4_out_ap_vld;
reg reg_3_out_ap_vld;
reg reg_2_out_ap_vld;
reg reg_1_out_ap_vld;
reg reg_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond153_fu_165_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] empty_fu_54;
wire   [3:0] empty_11_fu_171_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_p_load;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 empty_fu_54 = 4'd0;
#0 ap_done_reg = 1'b0;
end

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond153_fu_165_p2 == 1'd0)) begin
            empty_fu_54 <= empty_11_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_54 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_load = 4'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_1_out_ap_vld = 1'b1;
    end else begin
        reg_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_2_out_ap_vld = 1'b1;
    end else begin
        reg_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_3_out_ap_vld = 1'b1;
    end else begin
        reg_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_4_out_ap_vld = 1'b1;
    end else begin
        reg_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_5_out_ap_vld = 1'b1;
    end else begin
        reg_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_6_out_ap_vld = 1'b1;
    end else begin
        reg_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_7_out_ap_vld = 1'b1;
    end else begin
        reg_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_8_out_ap_vld = 1'b1;
    end else begin
        reg_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (exitcond153_fu_165_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        reg_out_ap_vld = 1'b1;
    end else begin
        reg_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_11_fu_171_p2 = (ap_sig_allocacmp_p_load + 4'd1);

assign exitcond153_fu_165_p2 = ((ap_sig_allocacmp_p_load == 4'd10) ? 1'b1 : 1'b0);

assign reg_1_out = 32'd0;

assign reg_2_out = 32'd0;

assign reg_3_out = 32'd0;

assign reg_4_out = 32'd0;

assign reg_5_out = 32'd0;

assign reg_6_out = 32'd0;

assign reg_7_out = 32'd0;

assign reg_8_out = 32'd0;

assign reg_out = 32'd0;

endmodule //fir_fir_Pipeline_1
